/* DO NOT EDIT THIS FILE - it is machine generated.
 * Except if there seems to be a blatant error ... */
#include <jni.h>
/* Header for class org_trifort_rootbeer_runtime_CUDAContext */

#ifndef _Included_org_trifort_rootbeer_runtime_CUDAContext
#define _Included_org_trifort_rootbeer_runtime_CUDAContext

#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_CUDAContext_cudaRun
(
    JNIEnv * env                   ,
    jobject  this_ref              ,
    jlong    nativeContext         ,
    jobject  object_mem            ,
    jint     using_kernel_templates,
    jobject  stats_row
);


#ifdef __cplusplus
}
#endif

#endif
