/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trifort_rootbeer_runtime_FixedMemory */

#ifndef _Included_org_trifort_rootbeer_runtime_FixedMemory
#define _Included_org_trifort_rootbeer_runtime_FixedMemory
#ifdef __cplusplus
extern "C" {
#endif

#define __FIXED_MEMORY_HEADER_WRAPPER( NAME, JTYPE )                    \
                                                                        \
JNIEXPORT void JNICALL                                                  \
Java_org_trifort_rootbeer_runtime_FixedMemory_doRead##NAME##Array       \
( JNIEnv *, jobject, JTYPE##Array, jlong, jint, jint );                 \
                                                                        \
JNIEXPORT void JNICALL                                                  \
Java_org_trifort_rootbeer_runtime_FixedMemory_doWrite##NAME##Array      \
( JNIEnv *, jobject, JTYPE##Array, jlong, jint, jint );                 \
                                                                        \
JNIEXPORT JTYPE JNICALL                                                 \
Java_org_trifort_rootbeer_runtime_FixedMemory_doRead##NAME              \
( JNIEnv *, jobject, jlong, jlong );                                    \
                                                                        \
JNIEXPORT void JNICALL                                                  \
Java_org_trifort_rootbeer_runtime_FixedMemory_doWrite##NAME             \
( JNIEnv *, jobject, jlong, JTYPE, jlong );

__FIXED_MEMORY_HEADER_WRAPPER( Byte   , jbyte    ) /* Signature: ([BJII)V */
__FIXED_MEMORY_HEADER_WRAPPER( Boolean, jboolean ) /* Signature: ([ZJII)V */
__FIXED_MEMORY_HEADER_WRAPPER( Short  , jshort   ) /* Signature: ([SJII)V */
__FIXED_MEMORY_HEADER_WRAPPER( Int    , jint     ) /* Signature: ([IJII)V */
__FIXED_MEMORY_HEADER_WRAPPER( Float  , jfloat   ) /* Signature: ([FJII)V */
__FIXED_MEMORY_HEADER_WRAPPER( Double , jdouble  ) /* Signature: ([DJII)V */
__FIXED_MEMORY_HEADER_WRAPPER( Long   , jlong    ) /* Signature: ([JJII)V */
/* doRead  -> sig: (JJ)B  */
/* doWrite -> sig: (JBJ)V */

#undef __FIXED_MEMORY_HEADER_WRAPPER

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    malloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_malloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
