#!/bin/sh

if [ -z "$CUDA_INC" ] || [ ! -d "$CUDA_INC" ]; then
    CUDA_INC=$(dirname $(which nvcc))/../include
    if [ ! -d "$CUDA_INC" ]; then
        CUDA_INC=/usr/local/cuda/include
    fi
    # The old version mixed -I/usr/local/cuda-5.5/include/ and /usr/local/cuda/include/
fi

compileSource() {
    while [ $# -ge 1 ]; do
        echo "compile $1.c"
        gcc -m64 -fPIC -g -c -o "$1.o"                   \
            -I'/usr/lib/jvm/default-java/include/'       \
            -I'/usr/lib/jvm/default-java/include/linux'  \
            -I"$CUDA_INC"                                \
            -Wall -Wextra -Wno-unused-parameter -std=c99 \
            "org/trifort/rootbeer/runtime/$1.c"
            # -DNDEBUG
        shift
    done
}
compileSource FixedMemory CUDARuntime CUDAContext Stopwatch PointerCasting

echo "Link rootbeer_x64.so.1"
gcc -m64 -shared -Wl,-soname,rootbeer -o rootbeer_x64.so.1 FixedMemory.o PointerCasting.o -lc

echo "Link rootbeer_cuda_x64.so.1"
gcc -m64 -shared -L'/usr/lib/nvidia-current/'           \
    -Wl,-soname,rootbeer_cuda -o rootbeer_cuda_x64.so.1 \
    CUDARuntime.o CUDAContext.o Stopwatch.o PointerCasting.o -lc -lcuda
