#!/bin/sh

if [ -z "$CUDA_INC" ]; then
    CUDA_INC=/usr/local/cuda/include/
fi

compileSource() {
    while [ $# -gt 1 ]; do
        gcc -fPIC -g -c -o "$1.o"                        \
            -I'/usr/lib/jvm/default-java/include/'       \
            -I'/usr/lib/jvm/default-java/include/linux'  \
            -I"$CUDA_INC"                                \
            -Wall -Wextra -Wno-unused-parameter \
            "org/trifort/rootbeer/runtime/$1.c"
            # -DNDEBUG
        shift
    done
}
compileSource FixedMemory CUDARuntime CUDAContext Stopwatch

gcc -shared -Wl,-soname,rootbeer -o rootbeer_x64.so.1 FixedMemory.o -lc

gcc -shared -L'/usr/lib/nvidia-current/'                \
    -Wl,-soname,rootbeer_cuda -o rootbeer_cuda_x64.so.1 \
    CUDARuntime.o CUDAContext.o Stopwatch.o -lc -lcuda
